name: maveshi
description: My Final Year Project in bachelors.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  #Others_plugins
  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  line_icons: ^2.0.1
  splash_screen_view: ^3.0.0
  animated_bottom_navigation_bar: ^1.1.0
  circular_reveal_animation: ^2.0.1
  auto_size_text: ^3.0.0
  flutter_vector_icons:
  persistent_bottom_nav_bar: ^5.0.2
  country_state_city_picker: ^1.2.8
  image_picker: ^0.8.6
  otp_text_field: ^1.1.3
  fluttertoast: ^8.2.1
  uuid: ^3.0.7
  intl: ^0.18.0
  url_launcher: ^6.1.11
  google_fonts:
  get: ^4.6.5
  google_maps_flutter: ^2.1.0


  #  flutter_localization: ^0.1.11
  #google map_plugins
  google_places_flutter: ^2.0.5
  geolocator: ^9.0.2
  geocoding: ^2.0.1
 #firebase_plugins
  firebase_messaging: ^14.6.2
  firebase_auth: ^4.2.6
  firebase_core:
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/pictures/
   - assets/icons/



  fonts:

    - family: Nisebuschgardens
      fonts:
        - asset: assets/fonts/Nisebuschgardens.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/NunitoBold.ttf


