import 'package:get/get.dart';

class LanguageServices extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "maveshi": "Maveshi",
          "home": "Home",
          "animals": "Animals",
          "drivers": "Drivers",
          "butcher": "Butcher",
          "doctors": "Doctors",
          "cow": "Cow",
          "buffalo": "Buffalo",
          "goat": "Goat",
          "lamb": "Lamb",
          "sheep": "Sheep",
          "other": "Other",
          "recommended for you": "Recommended for you",
          "join as butcher": "Join as Butcher",
          "join as doctor": "Join as Doctor",
          "join as driver": "Join as Driver",
          "sell your animal": "Sell Your Animal",
          "favourite list": "Favourite List",
          "language": "Language",
          "log out": "Log Out",
          "about us": "About Us",
          "search here": "Search here ...",
          "sign up": "Sign Up",
          "sign in": "Sign In",
          "view profile": "View Profile",
          "attention": "Attention!",
          "sign in please": "Sign In Please",
          "profile": "Profile",
          "search": "Search",
          "description": "Description",
          "price": "Price",
          "my post": "My Post",
          "contact": "Contact",
          "experience": "Experience",
          "call": "Call",
          "whatsapp": "Whatsapp",
          "getting started": "Getting Started",
          "seem your are new here!": "Seem you are new here!",
          "let's setup your profile": "Let's setup your profile",
          "name": "Name",
          "email": "Email",
          "forgot password": "Forgot Password",
          "password": "Password",
          "confirm Password": "Confirm Password",
          "let's sign you in": "Let's sign you in",
          "don't have an account": "Don't have an account",
          "welcome back you have been missed!": "Welcome you have been missed!",
          "register": "Register",
          "posts": "Posts",
          "bull": "Bull",
          "enter your name": "Enter Your Name",
          "please confirm your password": "Please confirm your Password!",
          "already have an account": "Already have an account",
          "for sale": "FOR SALE",
          "aboutus1":
              "Welcome to Maveshi, your trusted platform for buying and selling livestock and cattle. We are dedicated to connecting livestock farmers, traders, and enthusiasts from all around the world. Our mission is to simplify the process of livestock trading, ensuring transparency, convenience, and fair deals for all our users.",
          "aboutus2": "With Maveshi, you can",
          "aboutus3": "• Explore a wide range of livestock and cattle listings",
          "aboutus4": "• Connect with reputable livestock farmers and traders",
          "aboutus5": "• List your own livestock or cattle for sale",
          "aboutus6":
              "Join our community today and experience the convenience of buying and selling livestock and cattle with Maveshi!",
          "all mandi": "All pakistan Maveshi Mandis"
        },
        "ur_PK": {
          "for sale": "فروخت کے لئے",
          "view profile": "پروفائل",
          "maveshi": "مویشی",
          "home": "ھوم",
          "animals": "جانور",
          "drivers": "ڈرائیورز",
          "butcher": "قصاب",
          "doctors": "ویٹرنری ڈاکٹر",
          "cow": "گائے",
          "buffalo": "بھینس",
          "sheep": "بھیڑ",
          "goat": "بکری",
          "lamb": "میمنے",
          "other": " دوسرے جانور",
          "register": "رجسٹر کریں۔",
          "recommended for you": "آپ کیلئے تجویز کردہ",
          "let's sign you in": "آئیے آپ کو سائن ان کرتے ہیں۔",
          "welcome back you have been missed!":
              "خوش آمدید آپ کو یاد کیا گیا ہے!",
          "seem your are new here!": "لگتا ہے آپ یہاں نئے ہیں!",
          "let's setup your profile": "آئیے آپ کا پروفائل ترتیب دیں۔",
          "stories": "کہانیاں",
          "join as butcher": "قصاب کے طور پر شامل ہوں",
          "join as doctor": "ڈاکٹر کے طور پر شامل ہوں",
          "join as driver": "ڈرائیور کے طور پر شامل ہوں",
          "sell your animal": "اپنا جانور بیچو",
          "favourite list": "پسندیدہ فہرست",
          "language": "زبان",
          "log out": "لاگ آوٹ",
          "about us": "ہمارے بارے میں",
          "attention": "توجہ",
          "profile": "پروفائل",
          "sign up": "سائن اپ",
          "search": "تلاش کریں",
          "description": "تفصیل",
          "price": "قیمت",
          "age": "عمر",
          "weight": "وزن",
          "contact details": "رابطہ کی تفصیلات",
          "seller details": "بیچنے والے کی تفصیلات",
          "animal detail": "جانوروں کی تفصیل",
          "years old": "سالوں کا",
          "location": "مقام",
          "posts": "پوسٹس",
          "sign in": "سائن ان",
          "sign in please": "براہ کرم سائن ان کریں۔",
          "member since": "چونکہ اراکین",
          "date of birth": "پیدائش کی تاریخ",
          "gender": "صنف",
          "bull": "بیل",
          "getting started": "شروع ہوا چاہتا ہے",
          "enter your name": "اپنا نام درج کریں",
          "email": "ای میل",
          "enter your email": "اپنا ای میل درج کریں۔",
          "password": "پاس ورڈ",
          "please confirm your password":
              "براہ کرم اپنے پاس ورڈ کی تصدیق کریں۔",
          "already have an account": "پہلے سے ہی ایک اکاؤنٹ ہے",
          "name": "نام",
          "forgot password": "پاسورڈ بھول گے",
          "don't have an account": "اکاؤنٹ نہیں ہے",
          "aboutus1":
              "مویشیوں اور مویشیوں کی خرید و فروخت کے لیے آپ کے قابل اعتماد پلیٹ فارم Maveshi میں خوش آمدید۔ ہم دنیا بھر سے مویشیوں کے کسانوں، تاجروں اور شوقین افراد کو جوڑنے کے لیے وقف ہیں۔ ہمارا مشن لائیو سٹاک کی تجارت کے عمل کو آسان بنانا، اپنے تمام صارفین کے لیے شفافیت، سہولت اور منصفانہ سودے کو یقینی بنانا ہے۔",
          "aboutus2": "ماویشی کے ساتھ، آپ کر سکتے ہیں۔",
          "aboutus3":
              "• مویشیوں اور مویشیوں کی فہرستوں کی وسیع رینج کو دریافت کریں۔",
          "aboutus4": "• معروف مویشی پال کسانوں اور تاجروں کے ساتھ جڑیں'",
          "aboutus5": "• فروخت کے لیے اپنے مویشیوں یا مویشیوں کی فہرست بنائیں'",
          "aboutus6":
              "آج ہی ہماری کمیونٹی میں شامل ہوں اور ماویشی کے ساتھ مویشیوں اور مویشیوں کی خرید و فروخت کی سہولت کا تجربہ کریں!",
          "all mandi": "تمام پاکستانی ماویشی منڈی"
        }
      };
}
